AWSTemplateFormatVersion: 2010-09-09

Description: Security Groups

Parameters:
  EnvParamDB:
    Description: Your environment name
    Type: String

  InstanceTypeParam:
    Type: String
    # Default: t2.micro
    # AllowedValues:
    #   - t2.micro
    #   - t2.nano

  KeyNameParam:
    # Type: 'AWS::EC2::KeyPair::KeyName'
    Type: String

  AmazonImageIDParam:
    Type: String
    # Default: ami-051dfed8f67f095f5

  SubnetIdParam:
    Type: String

  SecurityGroupIdsParam:
    Type: String

  IamInstanceProfileParam:
    Type: String

Resources: 
    #DB Instance
  DBRDS:
    Type: AWS::EC2::Instance
    # DependsOn: AkSSMInstanceProfile
    Properties:
      ImageId: !Ref AmazonImageIDParam
      InstanceType: !Ref InstanceTypeParam
      KeyName: !Ref KeyNameParam
      SubnetId: !Ref SubnetIdParam 
      SecurityGroupIds:
        - !Ref SecurityGroupIdsParam
      IamInstanceProfile: !Ref IamInstanceProfileParam
      Tags:
        - Key: Name
          Value: !Join ["-", [ak, RDS, !Ref EnvParamDB]]
      UserData:
        Fn::Base64: |
            #!/bin/bash
            yum update -y
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
            db_name=`aws ssm get-parameter --name "/ak/db_name" --query 'Parameter.Value' --output text --region us-east-1`
            db_username=`aws ssm get-parameter --name "/ak/db_username" --query 'Parameter.Value' --output text --region us-east-1`
            db_user_password=`aws ssm get-parameter --name "/ak/user_password" --query 'Parameter.Value' --output text --region us-east-1`
            sudo amazon-linux-extras install -y lamp-mariadb10.2-php7.2
            sudo yum install mysql-server -y
            sudo systemctl enable mariadb
            sudo systemctl start mariadb
            mysql -h localhost -u root -e "create database $db_name"
            mysql -h localhost -u root -e "CREATE USER '$db_username'@'%' IDENTIFIED BY '$db_user_password'"
            mysql -h localhost -u root -e "GRANT ALL PRIVILEGES ON $db_name.* TO '$db_username'@'%' WITH GRANT OPTION"
            sudo yum -y install expect
            MYSQL_ROOT_PASS=admin
            sleep 5
            echo "Set root password"
            expect -f - <<-EOF
                set timeout 10
                spawn mysql_secure_installation
                expect "Enter current password for root (enter for none):"
                send -- "\r"
                expect "Set root password?"
                send -- "y\r"
                expect "New password:"
                send -- "${MYSQL_ROOT_PASS}\r"
                expect "Re-enter new password:"
                send -- "${MYSQL_ROOT_PASS}\r"
                expect "Remove anonymous users?"
                send -- "y\r"
                expect "Disallow root login remotely?"
                send -- "n\r"
                expect "Remove test database and access to it?"
                send -- "y\r"sudo
                expect "Reload privilege tables now?"
                send -- "y\r"
                expect eof
            EOF

Outputs:
  DBRDSOut:
    Description: DB instance id export to register in the NLB target group
    Value: !Ref DBRDS
